modLoader="javafml" 
loaderVersion="[28,)"

[[mods]]
modId="countdown"
version="${file.jarVersion}"
displayName="Countdown"
authors="xieao"
description='''
Like hardcore but limited time instead of limited lifes.
'''

#[[dependencies.countdown]]
#    modId="lollipop"
#    mandatory=true
#    versionRange="[0.0.2,)"
#    ordering="NONE"
#    side="BOTH"

[[dependencies.countdown]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.80,)"
    ordering="NONE"
    side="BOTH"